services:
  app:
    image: sim_api_image:latest
    container_name: sim_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    shm_size: "2gb"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./metrics:/app/metrics
      - ./simulation_results:/app/simulation_results
      - ./logs:/app/logs

  uploader:
    image: sim_uploader_image:latest
    container_name: sim_uploader
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./database/.env
    volumes:
      - ./database:/app
      - ./simulation_results:/app/simulation_results
    depends_on:
      - cloud-sql-proxy

  cloud-sql-proxy:
    container_name: cloud_sql_proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "cloudcomputing-fortgki-projekt:europe-west3:sim-db-pg-main"
    restart: unless-stopped
